### ISSUE TITLE
Metrics of ephemeral storage mismatch 

### ISSUE THREAD

**Issue by maifujalam** [jmcgrath207/k8s-ephemeral-storage-metrics#106]
I have a multi pod container named as daybook.
1. When I scrap metrics for each ephemeral storage  path  using ephemeral_storage_container_volume_usage as below:-
![image](https://github.com/user-attachments/assets/a830d373-220b-47cb-b886-2452700e071f)
that is 31 MB in total of all the paths.
2. When I scrap metrics using ephemeral_storage_pod_usage
![image](https://github.com/user-attachments/assets/55021f25-c77a-4bc4-9dca-2cf1bfe4269b)
Around 121 MB as pods ephemeral storage.
3. 
![image](https://github.com/user-attachments/assets/a4b99cca-d74a-471d-a79f-a58ec189088a)
But in the disk its 31MB.
So,where the extra MBs(around 90 MB)  are coming from in ephemeral_storage_pod_usage?

**Comment by jmcgrath207** [comment]
I do know that the cadisvor/kube API stats reflect slower than the filesystem, but I am leaning toward this being a non-issue unless your can present some other evidence or my testing is wrong.
 
 Right now I assuming it's being caused by this.
 https://github.com/jmcgrath207/k8s-ephemeral-storage-metrics/pull/104
 
 I will be releasing this soon.


#### Testing steps

```
kubectl exec -it -n ephemeral-metrics grow-test-7fc5884588-8tx9h -- /bin/bash
root@grow-test-7fc5884588-8tx9h:/# df -ah
Filesystem      Size  Used Avail Use% Mounted on
overlay          17G  1.6G   15G  10% /
proc               0     0     0    - /proc
tmpfs            64M     0   64M   0% /dev
devpts             0     0     0    - /dev/pts
sysfs              0     0     0    - /sys
cgroup             0     0     0    - /sys/fs/cgroup
mqueue             0     0     0    - /dev/mqueue
/dev/sda1        17G  1.6G   15G  10% /cache
/dev/sda1        17G  1.6G   15G  10% /cachez
shm              64M     0   64M   0% /dev/shm
/dev/sda1        17G  1.6G   15G  10% /dev/termination-log
/dev/sda1        17G  1.6G   15G  10% /etc/resolv.conf
/dev/sda1        17G  1.6G   15G  10% /etc/hostname
/dev/sda1        17G  1.6G   15G  10% /etc/hosts
tmpfs           3.7G   12K  3.7G   1% /run/secrets/kubernetes.io/serviceaccount
proc               0     0     0    - /proc/bus
proc               0     0     0    - /proc/fs
proc               0     0     0    - /proc/irq
proc               0     0     0    - /proc/sys
proc               0     0     0    - /proc/sysrq-trigger
tmpfs           1.9G     0  1.9G   0% /proc/asound
tmpfs           1.9G     0  1.9G   0% /proc/acpi
tmpfs            64M     0   64M   0% /proc/kcore
tmpfs            64M     0   64M   0% /proc/keys
tmpfs            64M     0   64M   0% /proc/timer_list
tmpfs           1.9G     0  1.9G   0% /proc/scsi
tmpfs           1.9G     0  1.9G   0% /sys/firmware
```

This `/cachez` maps to `cache-volume-four` in this deployment file.

https://github.com/jmcgrath207/k8s-ephemeral-storage-metrics/blob/master/chart/templates/test_deployments.yaml#L68

```
stat /cachez/
  File: /cachez/
  Size: 45056     	Blocks: 96         IO Block: 4096   directory
Device: 801h/2049d	Inode: 6297416     Links: 2
Access: (0777/drwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2024-08-02 07:38:54.865016373 +0000
Modify: 2024-08-02 07:39:34.626017015 +0000
Change: 2024-08-02 07:39:34.626017015 +0000
 Birth: 2024-08-02 07:24:33.684002485 +0000
```


Here is the raw query to get the volumes by podname (ex. `grow-test-6db9f95889-rsb9c`) 

```
kubectl get --raw "/api/v1/nodes/minikube/proxy/stats/summary" | jq '.pods |  to_entries | map(select(.value.podRef.name| match("grow-test-7fc5884588-8tx9h"))) | map(.value.volume)'
[
  [
    {
      "time": "2024-08-02T08:02:40Z",
      "availableBytes": 15425966080,
      "capacityBytes": 18160226304,
      "usedBytes": 9068544,
      "inodesFree": 10211936,
      "inodes": 10241360,
      "inodesUsed": 2187,
      "name": "cache-volume-two"
    },
    {
      "time": "2024-08-02T08:02:40Z",
      "availableBytes": 15425966080,
      "capacityBytes": 18160226304,
      "usedBytes": 9138176,
      "inodesFree": 10211936,
      "inodes": 10241360,
      "inodesUsed": 2204,
      "name": "cache-volume-four"
    },
    {
      "time": "2024-08-02T08:02:40Z",
      "availableBytes": 3904000000,
      "capacityBytes": 3904012288,
      "usedBytes": 12288,
      "inodesFree": 476555,
      "inodes": 476564,
      "inodesUsed": 9,
      "name": "kube-api-access-68rqt"
    }
  ]
]
```

Then we compared what was reporting in `exec`

```
/cachez# du -sb /cachez
9174784	/cachez
```

I also checked the Promethues query
```
ephemeral_storage_container_volume_usage{container="grow-test",mount_path="/cachez",node_name="minikube",pod_name="grow-test-7fc5884588-8tx9h",pod_namespace="ephemeral-metrics",volume_name="cache-volume-four"} 9.138176e+06
```
![image](https://github.com/user-attachments/assets/d21064d1-8794-4cb7-ae47-ff4a0d51e37b)


This results in  "usedBytes": 9138176` from `cache-volume-four` from the API query, `9174784` bytes from the `/cachez` filesystem path, and promethues metric of `9138176` bytes

`df -ah` Used space is not accurate compared to `du -sb` as we observed.

The CA advisor/kube api that we query in this library does lag behind the filesystem of the node from what I've observed.

**Comment by jmcgrath207** [comment]
Just released that fix.
